### ISSUE TITLE
Proposal Dynamic Table/Columns with Voting-System

### ISSUE THREAD

**Issue by Shinigami92** [tc39/proposals#156]
I'm not sure where to suggest it, so I'll write it here

How about if we provide a Tool like Trello in which we list the Proposals in the respective Stage and then the community can vote on what features they want mostly
For example, you could see which proposals are well received by the community and where priority could be given

If there is already a place for it, can you link it here please?

**Comment by Berkmann18** [comment]
This seems like a great idea especially when Trello has an addon for votes.

**Comment by Shinigami92** [comment]
Trello has this BUILT-IN :D

https://help.trello.com/article/788-voting-on-cards

**Comment by Berkmann18** [comment]
Oh, through power-ups.

**Comment by slikts** [comment]
There already is a voting mechanism through GitHub stars; they could just be collated into one table.

**Comment by dannyfritz** [comment]
I don't represent TC39, but I want to remind everyone that TC39 is a committee. Making public voting official would make people feel ignored that the most popular one wasn't worked on. Rust recently just went through this and had to explain to their community why they don't look at GitHub reaction counts. I understand you want a specific proposal to be fast tracked, but it is up to the respective champions to decide that.

**Comment by OussamaRomdhane** [comment]
@dannyfritz said it all.

I just want to add my two cents; features should not be based on popularity but rather stability and utility.

**Comment by Shinigami92** [comment]
@dannyfritz @OussamaRomdhane 
I understand you points
But I dont think popularity voting and stability/utility conflicts

It is chaired by the committee, but the committee can see which proposals are preferred

**Comment by lyleunderwood** [comment]
This is the most important part:

>Making public voting official would make people feel ignored that the most popular one wasn't worked on.

Any public and highly visible popularity-based metric which will necessarily and routinely be ignored by the committee for tons of reasons known and unknown will end up being mainly a point of conflict between the committee and the community.

**Comment by dietergeerts** [comment]
@lyleunderwood , true, but if reasons are given, then there is no reason to complain or feeling ignored, as they really looked at it. Imho, such a system would pinpoint features that the community are not waiting for, or don't find needed, thus work on them can be avoided and can go towards the other features.

**Comment by vcarl** [comment]
Even if most of respondents find and read the response, there will always be some who never saw it, don't read it fully, or feel wronged because their preferred proposal isn't being prioritized relative to the others. The [TC39 process](https://tc39.github.io/process-document/) doesn't have any criteria for demand or popularity, so I don't think the benefits outweigh the additional friction it's likely to cause.

**Comment by slikts** [comment]
The popularity contest already exists; I, for one, would find it interesting to have an overview of its results – even if it could shake the boat a little.

**Comment by TristanMarion** [comment]
You should check https://www.notion.so/, it is certain that they have something that will match with what you want 😄

**Comment by crutchcorn** [comment]
Honestly, I couldn't agree more with @dannyfritz, despite not being on TS39 either. Remember, sometimes adding more engineers to a project can slow it down, And take the case of the `global` proposal. They had gotten pretty far (was it Stage 3?) before someone pointed out compatability issues with the general web.

**Comment by dannyfritz** [comment]
The Rust team has thought a lot about this already and is an interesting read:
http://aturon.github.io/2018/05/25/listening-part-1/
http://aturon.github.io/2018/06/02/listening-part-2/
http://aturon.github.io/2018/06/18/listening-part-3/

**Comment by Shinigami92** [comment]
@dannyfritz So, if I understand that correctly, it's better to discuss something than just find something bad?
=> Yes, I am of the same opinion!

But with my suggestion, I did not want to adapt or replace any existing processes at all. I just wanted to suggest getting a little more/better overview and giving the community a better chance to prioritize/favor features/proposals

Proposal Trello cards should be linked in any case with discussions on GitHub

**Comment by tabatkins** [comment]
> I think that’s an appropriate level for "voting" — it’s vendors who will ultimately be interested in usage statistics and who will be determining priorities for implementation. Nobody benefits when spec development is driven by false urgency on the other hand.

Right - deciding implementation *prioritization* via, among other things, a voting/interest mechanism, makes some sense; the implementors have already vetted those topics during the standards-dev process, so there's little chance of getting something voted high that they don't actually want to do.  Trying to drive the feature development process itself via voting is problematic.

So a big :-1: on this idea from me too, with my many years of experience developing standards. I use dev feedback to help guide me on things that might be important to spec, but there's a lot of things devs really want that I'm simply never going to do, because they're impossible; a voting mechanism for CSS would just show that things like "a `:stuck:` pseudoclass" are popular despite being impossible.

**Comment by ljharb** [comment]
This seems answered.
