### ISSUE TITLE
Inconsistency in data type behaviors in javascript

### ISSUE THREAD

**Issue by skvijay007** [tc39/proposals#199]
Wierd behaviors,
1)
const x = {...a, key:true}
 
Throws error ‘a’ is undefined, but 

let a    //not assigned, which is undefined now

const x = {...a, key: true}

Doesn’t throw error even when typeof a is undefined

2)
Same goes with this scenario,

If we declare variable as undefined,

let a = undefined

And concatenate with other string,

let x = a + ‘test’ // outputs ‘undefinedtest’

Why is data type is getting concatenated?

**Comment by arcanis** [comment]
> Throws error ‘a’ is undefined, but [...]

It doesn't throw an error if `a` is `undefined` (as in, the variable exists but its value hasn't been set to anything) but only if `a` is *not defined* (as in, the program never even said there's a variable that match this name).

Only the later throws a `ReferenceError` exception because `undefined` is a value like any other (spreads are designed to just ignore it, and when concatenated they're just coerced into a string which gives `"undefined"`).

Worth nothing that this repository isn't meant for general questions about JS, you probably should ask on StackOverflow or similar next time 🙂
