### ISSUE TITLE
question: why doesn't Javascript have optional static typing ?

### ISSUE THREAD

**Issue by catastrop** [tc39/proposals#223]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by kyranet** [comment]
If I'm not wrong, this was attempted with ECMAScript 4th Edition, but it got discarded and released the 5th Edition. Many of the efforts in a statically typed JavaScript became [ActionScript](https://en.wikipedia.org/wiki/ActionScript). And there is a blog about [ES4](https://auth0.com/blog/the-real-story-behind-es4/).

JavaScript has evolved a lot since then, and the performance has increased greatly in all engines, clear and untyped JavaScript can be optimized to the point it's competitive against other languages that run on a VM, and TypeScript helps you with that as it can stop you from accidentally making functions polymorphic (V8 and probably other engines too).

With being able to pass type information to the engine, what do you mean? Most engines run heuristics to retrieve type information and generate optimized machine code from bytecode.

**Comment by catastrop** [comment]
@kyranet 
 I know this, but if Javascript has optional static typing, we don't have to use Typescript.

**Comment by kyranet** [comment]
Besides "not having to use TypeScript", what would be the usecase on this?

Don't get me wrong, I have been a TS user for over 2 years, and I really love it. I just want to see a good usecase for TS merging into JS other than removing a dependency.

**Comment by ORESoftware** [comment]
hard to improve on TypeScript at this point

**Comment by arcanis** [comment]
TypeScript still has rough edges or missing features when it comes to static typing. Every release fixes things or add new features that couldn't be polyfilled otherwise. It's easy for them, because every consumer has the choice of which version of TypeScript they want to use, and they'll be able to upgrade at the time of their choice.

On browsers, the situation is vastly different. You don't have control over the engine that executes your code. The only way to make things sane is to expect all environments to behave the exact same way for any valid code. As such, the consensus became that the TC39 work couldn't produce backward-incompatible changes - bugs and design flaws become by unfixable parts of the standard (that's why we have `.includes` and not `.contains`, for example).

And you could hardly find something with less bugs and design flaws than a type system on a dynamic language.

**Comment by catastrop** [comment]
JavaScript has types, but they are dynamic. we want optional static typing like Julia. Is this too hard to achieve?

**Comment by catastrop** [comment]
@kyranet, you love typescript, because it provides you optional static typing

**Comment by catastrop** [comment]
@arcanis, is having optional static typing on a dynamic language is too hard to do ? example Julia.

**Comment by TejasQ** [comment]
It’s not about difficult or easy from my perspective. It’s about performance and predictability. 

TypeScript has the freedom to introduce breaking changes because it’s just a tool. JS on the other hand, is a living standard that must always be backwards compatible. This makes adding such a concept, like optional static typing, incredibly tricky to get right and I’m not sure what value it would add that TypeScript already doesn’t add. 

Static type analysis also introduces a degree of slowdown that would not benefit JS. 

“But make it optional” — but TypeScript already has this. 

“But one less dev dependency” — but dev dependencies aren’t included in final production bundles, so what does it matter?

I don’t really see the point or the value this will add to the JS ecosystem to be honest. 

I think the peaceful coexistence between TypeScript and JavaScript is a good thing and makes the web better and I’d personally like to see it this way for the foreseeable future.

**Comment by catastrop** [comment]
>It’s not about difficult or easy from my perspective. It’s about performance and predictability  .

@TejasQ, 
how does optional static typing decrease performance and predictability.

**Comment by danShumway** [comment]
Let me turn the question around:

Given that Typescript already exists, and already does static typing, and given that Typescript is compiled and removed from your final codebase when you deploy it, what would be the major benefit of making this into a core feature?

What's something that you *can't* do in Typescript that you would theoretically be able to do if Javascript had static types?

I can think of a few things off the top of my head -- debug code without a sourcemap, for instance. But benefits like this have to be weighed against the downside of *greatly* increasing the core language complexity. Spec changes in JS are more costly and more dangerous than they are when they live in userland -- if we make mistakes on the web, we can't fix them later. I can only think of very minor benefits that a native type-enforcer would have over Typescript. I can't think of anything that seems so important that it would override the concerns I have with complicating and expanding the base language.

Another thing to keep in mind is that if your goal is to get away from Javascript's dynamic nature entirely -- ie, you want very strict typing that isn't optional, Javascript already has WASM.

Javascript is a runtime-compiled language, it doesn't have a compilation step during development. And compilation is the moment when type-checking is most useful. I would question then whether static type checking is even a good fit for core Javascript at all, or whether it would be better to look into something like Rust that can instead target WASM with less overhead.

**Comment by ljharb** [comment]
Closing, since this repo isn’t the proper place to have these discussions - please try es-discuss or our discourse. https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal / https://es.discourse.group
